CREATE TABLE comments (
    ID VARCHAR(10) PRIMARY KEY NOT NULL,
    PERMALINK VARCHAR(50) NOT NULL,
    DATE_ADDED INTEGER NOT NULL
);

CREATE TABLE statistics (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMENTS_CHECKED INT NOT NULL,
    COMMENTS_MATCHED INT NOT NULL,
    DATE_EXECUTED INTEGER NOT NULL
);

CREATE TABLE to_reply (
    ID VARCHAR(10) PRIMARY KEY NOT NULL,
    RESPONSE VARCHAR(50) NOT NULL
);

CREATE TABLE logs (
    LOG VARCHAR(100) NOT NULL,
    DATE_ADDED INTEGER NOT NULL
);
