CREATE TABLE comments (
    ID VARCHAR(10) PRIMARY KEY NOT NULL,
    PERMALINK VARCHAR(50) NOT NULL,
    DATE_ADDED INTEGER NOT NULL
);

CREATE TABLE to_reply (
    ID VARCHAR(10) PRIMARY KEY NOT NULL,
    RESPONSE VARCHAR(50) NOT NULL
);
