CREATE TABLE IF NOT EXISTS comments (
    ID VARCHAR(10) PRIMARY KEY NOT NULL,
    PERMALINK VARCHAR(50) NOT NULL,
    DATE_ADDED INTEGER NOT NULL,
    VALID BOOL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS to_reply (
    ID VARCHAR(10) PRIMARY KEY NOT NULL,
    RESPONSE VARCHAR(50) NOT NULL
);
